### ISSUE TITLE
Overlyrics won't get past "Starting..."

### ISSUE THREAD

**Issue by blu3c4t** [CezarGab/Overlyrics#5]
`C:\Users\A\Downloads\Overlyrics>python Overlyrics.py
HTTP Error for GET to https://api.spotify.com/v1/me/player/currently-playing with Params: {} returned 403 due to User not registered in the Developer Dashboard
Exception in thread Thread-1 (update_track_info):
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotipy\client.py", line 271, in _internal_call
    response.raise_for_status()
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/player/currently-playing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\A\Downloads\Overlyrics\Overlyrics.py", line 142, in update_track_info
    trackName, artistName, currentProgress, isPaused = get_track_info()
                                                       ^^^^^^^^^^^^^^^^
  File "C:\Users\A\Downloads\Overlyrics\Overlyrics.py", line 149, in get_track_info
    trackInfo = getCurrentTrackInfo()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\Downloads\Overlyrics\Overlyrics.py", line 110, in getCurrentTrackInfo
    current_track = sp.current_user_playing_track() # Get the information of the music being listened to, through the API
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotipy\client.py", line 1232, in current_user_playing_track
    return self._get("me/player/currently-playing")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotipy\client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotipy\client.py", line 293, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/player/currently-playing:
 User not registered in the Developer Dashboard, reason: None`

**Comment by CezarGab** [comment]
Hi there! Thank you very much for using my project.

Well, this error is caused because **the application uses the Spotify API, and is in development mode**. And there is a quota limit for the number of users, although it hasn't been exceeded. 

When I published the project, I checked with some accounts and was able to use the application normally. However, apparently I need to authorize manually the access for any account other than my own on the Spotify developer dashboard.

Anyway, let's try this: **send me your email (from your Spotify) and first name**, so that I can authorize you to use the application. **I don't need any account access or private information at all, just your email address to authorize it.** You can understand more about that situation [here](https://developer.spotify.com/documentation/web-api/concepts/quota-modes). 

Unfortunately, Github doesn't have private messaging functionality. So, in order for your e-mail address not be exposed on the site, send it here and I'll  censor the address as soon as I see it. 

Sorry for that non-ideal method. This won't be necessary when Spotify authorizes quota expansion, but I don't know when my submission will be accepted.

Is that okay for you? Let me know!

**Comment by blu3c4t** [comment]
Thanks for the reply! I wasn't exactly sure whether this was still an ongoing project so I wasn't expecting a response. 

The info you asked for: 
**[REDACTED]**@gmail.com
Nate

**Comment by blu3c4t** [comment]
oops misclicked

**Comment by CezarGab** [comment]
Done, Nate! I also already changed your comment to hide the email. 

Check if you're able to use Overlyrics now. Probably you'll have to authenticate again. Be sure your spotify account has the same email you have sent me.

**Comment by blu3c4t** [comment]
It works! Thanks mate!

**Comment by CezarGab** [comment]
You're welcome!

**Comment by xtho25** [comment]
Hello there! I am having the same problem here. It would be nice to authenticate me too, tell me whenever i can send my email.
Thanks in advance!

**Comment by CezarGab** [comment]
Hi @xtho25! Sorry for the inconvenience. 

Unfortunately, Spotify didn't approve my quota extension, so this method of manually adding the emails is still a thing. 

So please go ahead and post here your email address. I will invite you as soon as possible.

**Comment by xtho25** [comment]
Hello, no problem, i changed the auth system a bit to use the script but here is my email anyways: **[REDACTED]**@gmail.com 
xtho25 
Thanks!

**Comment by xtho25** [comment]
Thanks, it works, one more thing, make sure to delete the unedited comment for the person above to make the email not visible as it is still possible to see their email from the edited by dropdown menu.

**Comment by CezarGab** [comment]
Thank you xtho.
I didn't noticed the history.

Done here.

**Comment by AlfredoLezama** [comment]
I did not see this issues page until now, I'm sorry for authenticating more than once. I'm hoping that this project is still active so that you could approve my email as well. If so, I'll do my best to reply with my email as soon as I can.

**Comment by CezarGab** [comment]
Hi @AlfredoLezama! No problem if you tried to authenticate more than once. 

In order not to spam this issue, can you send me an email with your e-mail address? cezargabriel11@gmail.com 
I will add you as soon as possible.
 
Thanks!
